### ISSUE TITLE
Fehler in API Doku

### ISSUE THREAD

**Issue by bedlinger** [lmuehlboeck/wl-stoerungshistorie#1]
Beim Request für die disturbances sind die Paramter nicht start und end, sondern from und to für das Datum.

**Comment by lmuehlboeck** [comment]
Vielen Dank bedlinger!

**Comment by lmuehlboeck** [comment]
Readme aktualisiert

**Comment by bedlinger** [comment]
Vielen Dank noch einmal für den schnellen Fix!!! :)
