### ISSUE TITLE
Rechtschreibfehler in Readme

### ISSUE THREAD

**Issue by leanderlist** [lmuehlboeck/wl-stoerungshistorie#3]
Im ReadMe dieses Repositories befindet sich ein Rechtschreibfehler. Die Phrase "zu Verfügung" sollte zu "zur Verfügung" geändert werden, um die Regeln der deutschen Sprache anzuwenden.

**Comment by bedlinger** [comment]
Wow, was ein komischer Fehler in so einer tollen Dokumentation! Dieser Fehler ist mir nicht einmal aufgefallen, obwohl ich schon eine lange Historie an Issues in diesem Repo habe. Sehr gute Arbeit, Leander.

**Comment by lmuehlboeck** [comment]
Danke fürs Melden! Wurde mit f1ef3b9f1d54b930e8fc6a935f74b7c1cd8ee0ef verbessert.

**Comment by bedlinger** [comment]
Wow, ist dieser Maintainer schnell! Ich bin echt zufrieden mit @lmuehlboeck und seinem einzigartigen WL-Störungsarchiv. Echt ein toller Beitrag zu der Open-Source-Community.
