### ISSUE TITLE
Frontend Rechtschreibfehler in "Infos" Tab

### ISSUE THREAD

**Issue by leanderlist** [lmuehlboeck/wl-stoerungshistorie#4]
Auf der "Infos" Seite im Frontend sollte das wort "exestieren" zu "existieren" geändert werden, um so die Regeln der deutschen  Sprache korrekt zu befolgen.

**Comment by lmuehlboeck** [comment]
Verbessert mit 4226df56649659771e5f5b442aceb2e6bc948521

**Comment by bedlinger** [comment]
Wow, wieder echt schnell gefixt! 
Respekt @lmuehlboeck und @leanderlist  😎
